### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by djigit99**
Setup require module 'bs4' (todo: pip install --user . in working directory )
Use absolute path in args.
Run module in working directory

working directory = Metaprogramming

### CODE REVIEW

**Comment by dt-iss** [comment]
user@pc:~/Downloads/Metaprogramming-dev$ pip3 install
ERROR: You must give at least one requirement to install (see "pip help install")
user@pc:~/Downloads/Metaprogramming-dev$ pip3 install --user
ERROR: You must give at least one requirement to install (see "pip help install")

**Comment by dt-iss** [comment]
Project - https://github.com/PHPMailer/PHPMailer

user@pc:~/Downloads/Metaprogramming-dev$ python3 -m php_doc_gen -t /home/user/Downloads/ -r /home/user/Downloads/PHPMailer-master/ 
Could not open file!
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/Downloads/Metaprogramming-dev/php_doc_gen/__main__.py", line 32, in <module>
    Controller(Flags.p, Flags.t, True, True)
  File "/home/user/Downloads/Metaprogramming-dev/php_doc_gen/controller.py", line 64, in __init__
    doc_is_rec_folder(path, output_path, self.content, is_rec_search)
  File "/home/user/Downloads/Metaprogramming-dev/php_doc_gen/controller.py", line 52, in doc_is_rec_folder
    doc_rec_folder(path, output_path, content)
  File "/home/user/Downloads/Metaprogramming-dev/php_doc_gen/controller.py", line 39, in doc_rec_folder
    doc_folder(path, output_path, content)
  File "/home/user/Downloads/Metaprogramming-dev/php_doc_gen/controller.py", line 21, in doc_folder
    gen_preload(path, output_path)
  File "/home/user/Downloads/Metaprogramming-dev/php_doc_gen/generator.py", line 1567, in gen_preload
    os.makedirs(os.path.join(output_path, 'docs', 'css'), 777, True)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/user/Downloads/docs/css'

**Comment by dt-iss** [comment]
user@pc:~/Downloads/Metaprogramming-dev$ python3 -m php_doc_gen -t /home/user/Downloads/Perun/ -r /home/user/Downloads/Metaprogramming-dev/php_doc_gen/test/recFolder/
Could not open file!
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/Downloads/Metaprogramming-dev/php_doc_gen/__main__.py", line 32, in <module>
    Controller(Flags.p, Flags.t, True, True)
  File "/home/user/Downloads/Metaprogramming-dev/php_doc_gen/controller.py", line 64, in __init__
    doc_is_rec_folder(path, output_path, self.content, is_rec_search)
  File "/home/user/Downloads/Metaprogramming-dev/php_doc_gen/controller.py", line 52, in doc_is_rec_folder
    doc_rec_folder(path, output_path, content)
  File "/home/user/Downloads/Metaprogramming-dev/php_doc_gen/controller.py", line 39, in doc_rec_folder
    doc_folder(path, output_path, content)
  File "/home/user/Downloads/Metaprogramming-dev/php_doc_gen/controller.py", line 21, in doc_folder
    gen_preload(path, output_path)
  File "/home/user/Downloads/Metaprogramming-dev/php_doc_gen/generator.py", line 1567, in gen_preload
    os.makedirs(os.path.join(output_path, 'docs', 'css'), os.umask(0o007), True)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/user/Downloads/Perun/docs/css'

**Comment by dt-iss** [comment]
user@pc:~/Downloads/Metaprogramming-dev$ pip3 install .
Processing /home/user/Downloads/Metaprogramming-dev
Collecting bs4 (from php-doc-gen==1.0)
  Downloading https://files.pythonhosted.org/packages/10/ed/7e8b97591f6f456174139ec089c769f89a94a1a4025fe967691de971f314/bs4-0.0.1.tar.gz
Collecting beautifulsoup4 (from bs4->php-doc-gen==1.0)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/3b/c8/a55eb6ea11cd7e5ac4bacdf92bac4693b90d3ba79268be16527555e186f0/beautifulsoup4-4.8.1-py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 1.2MB/s 
Collecting soupsieve>=1.2 (from beautifulsoup4->bs4->php-doc-gen==1.0)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/81/94/03c0f04471fc245d08d0a99f7946ac228ca98da4fa75796c507f61e688c2/soupsieve-1.9.5-py2.py3-none-any.whl
Building wheels for collected packages: php-doc-gen, bs4
  Running setup.py bdist_wheel for php-doc-gen ... done
  Stored in directory: /home/user/.cache/pip/wheels/96/71/c0/765801eb74564c0d771c50eaae2b920297531974f8d33e02f6
  Running setup.py bdist_wheel for bs4 ... done
  Stored in directory: /home/user/.cache/pip/wheels/a0/b0/b2/4f80b9456b87abedbc0bf2d52235414c3467d8889be38dd472
Successfully built php-doc-gen bs4
Installing collected packages: soupsieve, beautifulsoup4, bs4, php-doc-gen
Successfully installed beautifulsoup4-4.8.1 bs4-0.0.1 php-doc-gen-1.0 soupsieve-1.9.5
user@pc:~/Downloads/Metaprogramming-dev$ php_doc_gen -h
bash: php_doc_gen: команду не знайдено
user@pc:~/Downloads/Metaprogramming-dev$ python3 php_doc_gen -h
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "php_doc_gen/__main__.py", line 1, in <module>
    from .controller import Controller
SystemError: Parent module '' not loaded, cannot perform relative import

**Comment by djigit99** [comment]
image
If you want to run php_doc_gen as module (I made module callable) you should use -m after python3.

**Pull request merged**
